config/routes.rb
Blog::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  # Define rotas do devise para o recurso users
  devise_for :users

  # Redireciona as actions login e logut para as devidas actions do Devise
  devise_scope :user do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
  end

  # Outras opções para autenticação com Devise
  #devise_for :admin_users, ActiveAdmin::Devise.config, ActiveAdmin::Devise.config

  # Bloco de definição de rotas para o recurso posts.
  resources :posts do
    collection do
      get 'search'
      get 'archive'
    end
  end

  # new, edit, show, index, create, destroy, update
  root :to => "posts#index"

  # Define as rotas (CRUD) para o recurso tags
  match "tags/:tag_id/posts" => "posts#index", :as => :tag_posts
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  has_and_belongs_to_many :tags
  accepts_nested_attributes_for :tags

  validates :title, :presence => true, :length => { :maximum => 140 }

  # valida o corpo da postagem (deve existir e não possui limite de tamanho)
  validates :body, :presence => true

  # Atualiza as tags relacionadas ao post
  def update_tags(tags_id)
    self.tags = []
    unless tags_id == nil
      tags_id[:id].each {|new_tag| self.tags << Tag.find(new_tag)}
    end
    self.save
  end

	def to_param
		"#{id} #{title}".parameterize
	end

  def self.search query
    result_posts = []

    Post.all.collect do |post|
      Post.relevant_terms(query).collect do |term|
        if (post.body.downcase.include? term.downcase or 
            post.title.downcase.include? term.downcase)
          result_posts << post
        end
      end
    end
    result_posts
  end

  def self.relevant_terms query
    query.strip!
    if query.include? ','
      query.gsub!(',', ' ')
    end
    term_list = query.split.collect! {|term| term.strip}
    Post.remove_stop_words(term_list)
  end

  def self.remove_stop_words term_list
    relevant_terms = []
    stop_words = Blog::Application.config.stop_words

    term_list.collect do |term|
      unless stop_words.include? term
        relevant_terms << term
      end
    end
    relevant_terms
  end

  def self.filter_archive(year, month)
    if year == nil and month == nil
      Post.all(:order => 'created_at DESC')
    elsif month == nil
      Post.all(:order=>"created_at DESC").group_by { |t| t.created_at.year.to_s}[year.to_s]
    elsif year == nil
      Post.all(:order=>"created_at DESC").group_by { |t| t.created_at.strftime("%m")}[month.to_s]
    else
      Post.all(:order=>"created_at DESC").group_by { |t| t.created_at.year.to_s + '.' +t.created_at.strftime('%m')}[year.to_s+'.'+month.to_s]
    end
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base

	has_and_belongs_to_many :posts

	# verifica se foi informado um nome para a tag
	validates :name, :presence => true, :length => 1..30

end

app/models/user.rb
class User < ActiveRecord::Base
  # Configura o Devise. Outras possíveis configurações são:
  # :token_authenticatable, :encryptable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :recoverable, :registerable,
  	     :rememberable, :confirmable

  # Configura atributos acessíveis.
  attr_accessible :email, :password, :password_confirmation, :remember_me,
  	              :username, :description, :profile_link

	# Associa usuário a suas postagens.
	has_many :posts

  # Valida unicidade da coluna email.
  validates_uniqueness_of :email

	# Valida o formato do e-mail.
	validates_format_of :email, :with => /\A[A-Za-z0-9._%+-]+@redu.com.br/

	# Valida formato da senha.
	validates :password, :length => { :minimum => 5 }, :unless => "password.blank?"

	# Valida descrição.
	validates :description, :length => 50..90

	# Valida link do perfil do Redu.
	validates :profile_link, :presence => true
	validates_format_of :profile_link,
							        :with => /http:\/\/[www.]*redu.com.br\/pessoas\/[a-zA-Z_0-9]+/,
							        :message => '(é necessário informar um link de perfil válido)'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper TextHelper

  before_filter :store_location

  def store_location
    session[:user_return_to] = "/admin" # request.url unless params[:controller] == "devise/sessions"
    # If devise model is not User, then replace :user_return_to with :{your devise model}_return_to
  end

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || root_path
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :show, :search, :archive]

  def index
    @posts = params[:tag_id] ? Tag.find(params[:tag_id]).posts : Post.all(:order => 'created_at DESC')
    @tags = Tag.all
      respond_to do |format|
        format.html {render :layout => params[:tag_id] ? 'tag' : true}
        format.rss {render :layout => false } #feed.rss.builder
      end
  end

  def new
    @post = Post.new
    @post.tags.build
    respond_to do |format|
      format.html  # new.html.erb
    end
  end

  def create
    @post = Post.new(params[:post])
    params[:tag]["id"].delete('')
    @post.update_tags(params[:tag])
    @post.user_id = current_user.id
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post }
      else
        format.html { render :action => 'new' }
      end
    end
  end

  def edit
    @post = Post.find(params[:id])
    @post.tags.build
  end

  def update
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update_attributes(params[:post])
        @post.update_tags params[:tag]
        format.html { redirect_to @post }
      else
        format.html { render :action => 'edit' }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "Successfully destroyed post."
    redirect_to posts_path
  end

  def show
    @post = Post.find(params[:id])
    # @tags = @post.tags by embs
    @tags = Tag.all
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def search
    @posts = Post.search params[:search]
  end

  def archive
    @tags = Tag.all
    @posts = Post.filter_archive(params[:year], params[:month])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/text_helper.rb
module TextHelper

  def markparser
    parser = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
                                        :autolink => true,
                                        :space_after_headers => false)

    parser
  end

  def truncate_html(html)
    parsed = Nokogiri::HTML(html)
    count = 0
    parsed.xpath("//body").children.each do |child|
      child.remove if count > 5
      count = count + 1
    end

    parsed.to_html
  end

  def truncate_html_tag(html_text, tag)
    parsed = Nokogiri::HTML(html_text)
    parsed.xpath("//"+tag).each do |img|
      img.remove
      img.text.gsub(/\s+/, " ").strip
    end

    parsed.to_html
  end

end

module NokogiriTruncator
  module NodeWithChildren
    def truncate(max_length)
      return self if inner_text.length <= max_length
      truncated_node = self.dup
      truncated_node.children.remove

      self.children.each do |node|
        remaining_length = max_length - truncated_node.inner_text.length
        break if remaining_length <= 0
        truncated_node.add_child node.truncate(remaining_length)
      end
      truncated_node
    end
  end

  module TextNode
    def truncate(max_length)
      Nokogiri::XML::Text.new(content[0..(max_length - 1)], parent)
    end
  end

end

Nokogiri::HTML::DocumentFragment.send(:include, NokogiriTruncator::NodeWithChildren)
Nokogiri::XML::Element.send(:include, NokogiriTruncator::NodeWithChildren)
Nokogiri::XML::Text.send(:include, NokogiriTruncator::TextNode)

app/helpers/wymeditor_helper.rb
module WymeditorHelper
	def wymeditor_initialize(*dom_ids)
		output = []
		unless(Rails.env =~ /(production)|(test)/)
			output << javascript_include_tag('/javascripts/wymeditor/wymeditor/jquery.wymeditor.js')
		else
			output << javascript_include_tag('/javascripts/wymeditor/wymeditor/jquery.wymeditor.pack.js')
		end
		output << javascript_include_tag('/javascripts/wymrails.js')
		output.join("\n")
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
    <title>Blog Redu</title>
    <link rel="shortcut icon" href="/favicon.ico" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" 
            type="text/javascript"></script>
    <script type="text/javascript" src="http://use.typekit.com/lpo4rgu.js"></script>
    <script type="text/javascript">try{ Typekit.load(); }catch(e){}</script>

    <!-- Google Analytics -->
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-13202852-2']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="overlay">
      <div class="body container_16">
        <div class="logo-top">
          <div class="imagem">
            <%= link_to 'blog', root_path %>
            <span class="blog">blog</span>
          </div>
          <span class="tecoteco">Teco Teco</span>
        </div>
        <div class="body-blog omega alfa grid_16">
        <% flash.each do |key, value| %>
          <li><%= content_tag(:div, value, :class => "flash #{key}") %></li>
        <% end %>
          <%= yield %>
        </div>
      </div>
      <div class="push"></div>
    </div>
    <%= render :partial => "shared/footer" %>
  </body>
</html>

app/views/layouts/tag.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
    <title>Blog Redu</title>
    <link rel="shortcut icon" href="/favicon.ico" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" 
            type="text/javascript"></script>
    <script type="text/javascript" src="http://use.typekit.com/lpo4rgu.js"></script>
    <script type="text/javascript">try{ Typekit.load(); }catch(e){}</script>
    
    <!-- Google Analytics -->
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-13202852-2']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="overlay">
      <div class="body container_16">
        <div class="logo-top">
          <div class="imagem">
            <%= link_to 'blog', root_path %>
            <span class="blog">blog</span>
          </div>
          <span class="tecoteco">Teco Teco</span>
        </div>
        <div class="body-blog omega alfa grid_16">
          <div class="tags-page">
            <ul class="itens-tags-page">
              <li class="tag-page">
                <%= link_to 'blog', root_path %>
                <span class="bar"> /</span>
              </li>
              <li class="tag-page">
                <a>marcadores</a>
                <span class="bar"> /</span>
              </li>
              <li class="tag-page">
                <%= link_to Tag.find(params[:tag_id]).name.downcase, tag_posts_path(params[:tag_id]) %>
              </li>
            </ul>
          </div>
          <%= yield %>
        </div>
        <div class="push"></div>
      </div>
    </div>
    <%= render :partial => "shared/footer" %>
  </body>
</html>

app/views/posts/_author_link.html.erb
<%= post.user == nil ? 'Desconhecido' : link_to(post.user.username, 
                                                post.user.profile_link, 
                                                :class => 'link-author') %>

app/views/posts/_edit_or_delete_post_links.html.erb
<% if current_user %>
  <%= link_to "Editar Postagem", edit_post_path(post) %> || 
  <%= link_to "Apagar Postagem", "/posts/#{post.id}", 
              :method => :delete, 
              :confirm => "Tem certeza que quer apagar a postagem?" %> 
<% end %>

app/views/posts/_form.html.erb
<%= raw wymeditor_initialize %>
<%= form_for(@post) do |form| %>

  <div>
    <%= form.label :title %><br />
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %><br />
    <%= form.text_area :body, :class => 'wymeditor' %>
  </div>

	<br />
  <%= render :partial => 'posts/use_tag',
     :locals => { :form => form } %>
  <br/>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/posts/_post_date.html.erb
<span class="date grid_1 omega alfa">
  <span class="day"><%= post.created_at.to_datetime.strftime('%d') %></span>
  <span class="month">
    <%= (l post.created_at.to_datetime, :format => ("%b")).downcase %>
  </span>
  <span class="year">
    <%= post.created_at.year %>
  </span>
</span>

app/views/posts/_post_preview.html.erb
<li class="post grid_12 omega alfa">
  <%= render :partial => 'posts/post_date',
             :locals => { :post => post_preview } %>
   <div class="box-title grid_11 alfa omega">
    <%= link_to post_preview.title, post_preview, :class => "title grid_10" %>
  </div>
  <div class="grid_11 omega alfa informations">
    <div class="author alfa omega grid_4">
      <span class="add-informations">
        por <%= render :partial => 'author_link',
                       :locals => { :post => post_preview} %>
      <span class="add-informations">
        <%= post_preview.created_at.to_datetime.strftime(", às %H:%M") %>
    </span></span>
  </div>
  <ul class="tags omega grid_6">
    <% post_preview.tags.each do |tag| %>
      <li><%= link_to tag.name, tag_posts_path(tag), :class => "tag" %></li>
    <% end %>
  </ul>
</div>
<div class="text-box alfa omega grid_11">
  <div class="text alfa omega">
    <% text = markparser.render(post_preview.body) %>
    <%= raw truncate_html(truncate_html_tag(text, "img")) %>
    <%= link_to " + leia mais", post_preview, :class => "read-more" %>
    <%= render :partial => 'edit_or_delete_post_links',
               :locals => { :post => post_preview } %>
  </div>
</div>
</li>

app/views/posts/_tags.html.erb
<div>
  <%= select ('tag', 'id', options_for_select(Tag.all.collect {|t| [t.name, t.id]}, :selected => @post.tags.all.collect {|t| t.id}), {}, :multiple => '', :class => 'chzn-select', :style => 'width: 300px', 'data-placeholder' => 'Select a tag') %>
</div>

<script type="text/javascript"> $(".chzn-select").chosen(); $(".chzn-select-deselect").chosen({allow_single_deselect:true}); </script>

app/views/posts/_use_tag.html.erb
<div>
  <%= select ('tag', 'id', 
              options_for_select(Tag.all.collect {|t| [t.name, t.id]}, 
                                 :selected => @post.tags.all.collect {|t| t.id}), {}, 
                                 :multiple => '', :class => 'chzn-select', 
                                 :style => 'width: 300px', 
                                 'data-placeholder' => 'Select a tag') %>
</div>

<script type="text/javascript"> 
  $(".chzn-select").chosen(); 
  $(".chzn-select-deselect").chosen({allow_single_deselect:true}); 
</script>

app/views/posts/archive.html.erb
<div class="files-page">
  <ul class="itens-files-page">
    <li class="file-page">
      <%= link_to 'blog', root_path %>
      <span class="bar"> /</span>
    </li>
    <li class="file-page">
      <a>arquivos</a>
      <span class="bar"> /</span>
    </li>
    <% if params[:year] %>
      <li class="file-page"><!-- year -->
        <%= link_to params[:year].to_s, {:controller => :posts, :action => 'archive', 
                                         :year => params[:year] } %>
        <% if params[:month] %>
          <span class="bar"> /</span>
        <% end %>
      </li>
   <% end %>
   <% if params[:month] %>
     <li class="file-page"><!-- month -->
       <%= link_to(
          (l Date.today.beginning_of_year.advance(:months => (params[:month].to_i-1)), 
           :format => "%B").downcase, 
          {:controller => :posts, :action => 'archive', :month => params[:month] }) %>
     </li>
   <% end %>
  </ul>
</div><!-- end navbar -->

<div class="box-posts omega alfa grid_12">
  <ol class="posts omega alfa">
    <%= render :partial => 'post_preview', :collection => @posts %>
  </ol>
</div>
<%= render :partial => "shared/sidebar", :locals => { :members => false } %>
<div class="push"></div>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render 'form' %>
<br />

<div>
  <%= link_to 'Back', posts_path %>
</div>
<div class='push'></div>

app/views/posts/index.html.erb
<div class="box-posts omega alfa grid_12">
  <ol class="posts omega alfa">

    <%= render :partial => "post_preview", :collection => @posts %>
  </ol>
</div>
<%= render :partial => "shared/sidebar", 
           :locals => { :members => (true unless params[:tag_id]) } %>
<div class="push"></div>
<%# link_to 'Mostrar Mais...', root_path,
          :class =>  "link-show-more icon-seta-gray_8_12-before show-more grid_3" %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<br />

<div>
  <%= link_to 'Back', posts_path %>
</div>
<div class='push'></div>

app/views/posts/search.html.erb
<h1> Results </h1>
<ul>
<% @posts.each do |post| %>
	<li><%= link_to post.title, post %></li>
<% end %>
</ul>

<% if user_signed_in? %>
  <%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
<% else %>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="posts-page">
  <ul class="itens-posts-page">
    <li class="post-page">
      <%= link_to 'blog', root_path %><span class="bar"> /</span>
    </li>
    <li class="post-page"><%= link_to 'post', @post %></li>
  </ul>
</div>

<div class="box-posts omega alfa grid_12">
  <ol class="posts omega alfa">
    <li class="post grid_12 omega alfa">
      <%= render :partial => 'posts/post_date',
                 :locals => { :post => @post } %>
      <div class="box-title grid_11 alfa omega">
        <%= link_to @post.title, @post, :class => 'title grid_10' %>
      </div>
      <div class="grid_11 omega alfa informations">
        <div class="author alfa omega grid_4">
          <span class="add-informations">
            por <%= render :partial => 'author_link', :locals => { :post => @post} %>
            <span class="add-informations">
              <%= @post.created_at.to_datetime.strftime(", às %H:%M") %>
            </span>
          </span>
        </div>
        <ul class="tags omega grid_6">
          <% if @post.tags.size > 0 %>
            <% @post.tags.all.collect do |tag| %>
              <li><%= link_to tag.name, tag_posts_path(tag), :class => 'tag'%></li>
            <% end %>
          <% end %>
        </ul>
      </div>
      <div class="text-box text-box-post alfa omega grid_11">
        <%= raw markparser.render(@post.body) %>
      </div>
      <%= render :partial => 'edit_or_delete_post_links',
           :locals => { :post => @post } %>
    </li>
  </ol>
</div>
<%= render :partial => "shared/sidebar", :locals => { :members => false } %>
<div class='push'></div>

app/views/shared/_block_archive.html.erb
<div class="files grid_4">
  <h1 class="title">Arquivos</h1>
  <%
  hash_archive = Post.all(:order => 'created_at DESC')
  group_years = hash_archive.group_by{ |p| p.created_at.year}
  group_years.keys.each do |key|
  %>
  <ul class="years">
    <li class="year"><%= key %></li>
    <ul class="months">
      <% group_years[key].group_by { |post| l post.created_at, 
                                     :format=>('%B,%m')}.keys.each do |month| %>
        <li class="month">
          <%= link_to month.split(',')[0], {:controller => :posts, 
                                            :action => 'archive', :year=>key, 
                                            :month => month.split(',')[1]} %>
        </li>
      <% end %>
    </ul>
  <% end %>
  </ul>
</div>

app/views/shared/_block_members.html.erb
<div class="grid_4 alfa some-users">
  <ul class="about-us grid_4 omega alfa">
    <li class="title">Quem Somos </li>
    <% User.all.shuffle.each do |user| %>
      <li class="member">
        <%= link_to user.username, user.profile_link, :class => "link-member" %>
        <span class="description grid_3">
          <%= user.description %>
        </span>
      </li>
    <% end %>
  </ul>
  <span>
    <%= link_to "Espera aí, tem mais!", "#redunianos", :class => "stop-here grid_3" %>
  </span>
</div>

app/views/shared/_block_tags.html.erb
<div class="box-marks alfa grid_4">
  <ul class="marks alfa omega grid_4">
    <li class="title"> Marcadores </li>
    <% @tags.find_all {|tag| tag.posts.size > 0}.each do |tag_list|  %>
      <li class="mark">
        <%= link_to tag_list.name, tag_posts_path(tag_list)  %>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container_16">
    <div class="imagens-inferior">
      <span class="zepi">Zepi</span>
      <span class="html5">html5</span>
    </div>
    <h1 class="logo-bottom"><a href="http://www.redu.com.br"></a></h1>
    <p class="presentation-call">
      Somos uma startup brasileira, recifense e estamos incubados pelo Porto Digital. 
      Nossa equipe é composta por pessoas dedicadas e comprometidas com um objetivo 
      em comum: desenvolver produtos que façam a diferença para uma educação mais 
      acessível e universal.
    </p>
    <address class="our-address">
      Av. Barbosa Lima, 149, sala 413, Recife Brasil CNPJ: 12.359.885/0001-07
    </address>
    <ul class="about-redu">
      <li class="item-menu">
        <a href="http://blog.redu.com.br/">Visite nosso Blog</a>
      </li>
      <li class="item-menu">
        <a href="http://blog.redu.com.br/">Página Inicial</a>
      </li>
    </ul>
    <ul class="politics-terms">
      <li class="item-menu">
        <a href="http://blog.redu.com.br/">Termos de Uso</a>
      </li>
      <li class="item-menu">
        <a href="http://blog.redu.com.br/">Política de Privacidade</a>
      </li>
      <li class="item-menu">
        <a href="http://blog.redu.com.br/">Fale Conosco</a>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="grid_4  alfa omega sidebar">
  <%= render :partial => "shared/block_members" if members %>
  <%= render :partial => "shared/block_tags" %>
  <%= render :partial => "shared/block_archive" %>

  <div class="partners alfa grid_4">
    <h1 class="title">Parceiros</h1>
    <h3 class="partner-pd omega alfa grid_2">
      <%= link_to "Porto Digital", "http://www.portodigital.org/" %>
    </h3>
    <h3 class="partner-cns omega alfa grid_2">
    </h3>
    </h3>
    <h3 class="partner-ccte omega alfa grid_2">
      <%= link_to "CTTE", "http://www.cin.ufpe.br/~ccte/" %>
    </h3>
    <h3 class="partner-for omega alfa grid_2">
      <%= link_to "Frevo on Rails", "http://www.frevoonrails.com.br/" %>
    </h3>
  </div>
</div>

app/views/tags/_form.html.erb
<div>
  <%= select ('tag', 'id', options_for_select(Tag.all.collect {|t| [t.name, t.id]}, :selected => @post.tags.all.collect {|t| t.id}), {}, :multiple => '', :class => 'chzn-select', :style => 'width: 300px', 'data-placeholder' => 'Select a tag') %>
</div>

<script type="text/javascript"> $(".chzn-select").chosen(); $(".chzn-select-deselect").chosen({allow_single_deselect:true}); </script>